### ISSUE TITLE
# Ensure access role created is attached even if no values are provided via `var.source_configuration` doesnt work as expected

### ISSUE THREAD

**Issue by ankithriday** [terraform-aws-modules/terraform-aws-app-runner#9]
## Description

Passing create_access_iam_role=true and source_configuration doesn't include the authentication_configuration attribute.

source_configuration = local.create_access_iam_role ? merge(
    var.source_configuration,
    { authentication_configuration = { access_role_arn = aws_iam_role.access[0].arn } }
  ) : var.source_configuration

The above evaluation fails this is because
merge(
    var.source_configuration,
    { authentication_configuration = { access_role_arn = aws_iam_role.access[0].arn } }
  ) 
has an authentication_configuration attribute, but the false side var.source_configuration doesn't.

Terraform complains with The true and false result expression must have consistent types. The 'true' value includes object attribute "authentication_configuration", which is absent in the 'false' value

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 1.2.0

- Terraform version: Tried both 1.3.1 and 1.5.2

- Provider version(s): aws version 5.6.2

## Reproduction Code [Required]

create_access_iam_role=true

source_configuration={
  auto_deployment_enabled = false
  image_repository={
    image_configuration = {
      port = 80
    },
    image_identifier="some_ecr_repo_in_same_account"
    image_repository_type="ECR"
  }
}

access_iam_role_policies = {
  'ecracccess' = 'pre-existing-policy-arn'
}

 no
 Yes
 Passing create_access_iam_role=true and source_configuration doesn't include the authentication_configuration attribute.

## Additional context

I think the way above line of code is done, might need to reevaluated

**Comment by ahummel25** [comment]
@ankithriday I'm also experiencing this same exact issue. Did you find any solution?

**Comment by thebigcosinus** [comment]
Hi,

@ahummel25  @ankithriday  Did you find a solutuion regarding this issue ?

`The true and false result expressions must have consistent types. The 'true' value includes object attribute "authentication_configuration", which is absent in the 'false' value.
`

**Comment by vanrijm** [comment]
I am also experiencing this issue. Are there any work arounds?

**Comment by thebigcosinus** [comment]
@vanrijm I added authentication_configuration = null in the source_configuration

source_configuration = {
    **authentication_configuration = null**
    auto_deployments_enabled     = false
    image_repository = {
